version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./database.db:/app/database.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  database: